version: "3.9"

services:
  terminal-backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: terminal_backend
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true
